version: '3.0'

services:
 ui:
  image: apatterson189/social-media:ui
  ports:
  - "80:80"
  depends_on:
    - api

 api:
  image: apatterson189/social-media:api-express
  ports:
  - "9000:9000"
  depends_on:
    - database

 database:
  image: mongo
  ports:
  - "27017:27017"

